---

################################################################################
# Vault-related options
################################################################################

# The mountpoint of the kv secrets engine
bbcrd_vault_kv_mount: secret

# The Vault token to use. Must have sufficient privileges to configure secrets
# engines, identities and policies.
#
#bbcrd_vault_root_token: "..."


################################################################################
# KV secrets engine config
################################################################################

# The version of the kv secrets engine.
#
# Warning: changing this will cause the engine (and its secrets) to be deleted
# and replaced with a new one.
bbcrd_vault_kv_version: 1

# The name of the policy to create which grants full read/write access to all
# secrets.
bbcrd_vault_kv_admin_policy_name: "kv_admin"

# The name of the policy to create which grants read-only access to all
# secrets.
bbcrd_vault_kv_read_only_policy_name: "kv_read_only"
