---
# The following may be set to override the behaviour of this playbook:
#
# * ansible_vault_cluster_ansible_group_name -- Change the group of hosts to
#   run against
#
# * playbook_administrator_name -- The name of the administrator whose public
#   keys will used in the playbook (via ansible_vault_pgp_key_fingerprints)
#
# * enabled_administrators -- The set of administrators whose public keys are
#   included in the Ansible data in ansible_vault_administrators. Defaults to
#   ['test-user-1'].

- name: Set PGP variables
  hosts: "{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  tasks:
    - name: "Set ansible_vault_administrators and ansible_vault_pgp_key_fingerprints"
      import_tasks: set_pgp_variables.yml
      tags: always
  
- name: Run main vault installation/management playbook
  import_playbook: bbcrd.ansible_vault.manage_vault_cluster


- name: Clean up any non-cluster memebers
  hosts: "all,!{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  tasks:
    - name: Shutdown vault server
      systemd:
        name: vault
        state: stopped
      ignore_errors: true  # Vault may not be installed
      tags: always
    
    - name: Delete all vault data
      file:
        path: /var/lib/vault
        state: absent
      tags: always
