---

# The following tasks set the bbcrd_vault_administrators and
# bbcrd_vault_pgp_key_fingerprints variables according to:
#
# * playbook_administrator_name -- The name of the administrator whose public
#   keys will used in the playbook (via bbcrd_vault_pgp_key_fingerprints)
#
# * enabled_administrators -- The set of administrators whose public keys are
#   included in the Ansible data in bbcrd_vault_administrators. Defaults to
#   ['test-user-1'].

- name: Remove public keys from bbcrd_vault_administrators
  run_once: true
  set_fact:
    bbcrd_vault_administrators: |-
      {{
        bbcrd_vault_administrators.keys()
          | zip(
            bbcrd_vault_administrators.values()
              | map('combine', {'bbcrd_vault_pgp_public_key': omit})
            )
          | community.general.dict
      }}

- name: Import selected public keys into bbcrd_vault_administrators
  run_once: true
  set_fact:
    bbcrd_vault_administrators: |-
      {{
        bbcrd_vault_administrators
          | combine(
              (
                lookup(
                  'ansible.builtin.file',
                  lookup('env', 'GNUPGHOME') ~ '/bbcrd_vault_administrators_' ~ item ~ '.yml',
                ) | from_yaml
              ).bbcrd_vault_administrators,
              recursive=True,
            )
      }}
  loop: "{{ enabled_administrators | default(['test-user-1']) }}"
  loop_control:
    label: "{{ lookup('env', 'GNUPGHOME') }}/bbcrd_vault_administrators_{{ item }}.yml"

- name: Set bbcrd_vault_pgp_key_fingerprints
  run_once: true
  set_fact:
    bbcrd_vault_pgp_key_fingerprints: >-
      {{
        [
          bbcrd_vault_administrators
            [playbook_administrator_name | default('test-user-1')]
            .bbcrd_vault_pgp_public_key
            | bbcrd.vault.ascii_armor_to_base64
            | bbcrd.vault.pgp_public_key_to_fingerprint
        ]
      }}
