---


# NB: This role fails if the encrypted unseal keys on the other servers are
# already inconsistent
- name: Fetch encrypted unseal keys
  import_role:
    name: bbcrd.vault.decrypt_unseal_keys
    tasks_from: fetch.yml

- name: Propagate encrypted unseal keys to new nodes
  copy:
    content: "{{ encrypted_unseal_keys | to_nice_json }}"
    dest: "{{ ansible_vault_config_dir }}/encrypted_unseal_keys.json"
    force: false  # Only write to hosts which don't already have keys installed
    backup: true  # Redundant, but I'm paranoid
