namespace: "bbcrd"
name: "vault"
version: "1.4.1"
readme: "README.md"
authors:
  - "Jonathan Heathcote <jonathan.heathcote@bbc.co.uk>"
license-file: LICENSE
tags:
  - collection
  - vault
  - hashicorp
repository: "https://www.github.com/bbc/bbcrd_vault_collection"
