namespace: "bbcrd"
name: "vault"
version: "0.0.14"
readme: "README.md"
authors:
  - "Jonathan Heathcote <jonathan.heathcote@bbc.co.uk>"
license:
  - MIT
tags:
  - collection,
  - vault,
  - hashicorp
repository: "https://www.github.com/bbc/bbcrd_bbcrd_vault_collection"
