namespace: "bbcrd"
name: "vault"
version: "0.0.12"
readme: "README.md"
authors:
  - "Jonathan Heathcote <jonathan.heathcote@bbc.co.uk>"
license-file: LICENSE
tags:
  - collection,
  - vault,
  - hashicorp
repository: "https://www.github.com/bbc/bbcrd_bbcrd_vault_collection"
