namespace: "bbcrd"
name: "ansible_vault"
version: "0.0.1"
readme: "README.md"
authors:
  - "Jonathan Heathcote <jonathan.heathcote@bbc.co.uk>"
dependencies:
license-file: LICENSE
tags:
  - collection,
  - vault,
  - hashicorp
repository: "https://www.github.com/bbc/bbcrd_ansible_vault_collection"
