---
- name: Corrupt backup credentials on one server
  hosts: vault-1
  
  tasks:
    
    - name: Corrupt backup credentials
      lineinfile:
        path: /etc/vault_backup_credentials.env
        regexp: '^ROLE_ID='
        line: ROLE_ID=xxx
