---

# Override: If set to True, rekey the unseal keys even if the set of managers
# has not changed.
ansible_vault_force_rekey: false

# When set, do not interactively prompt for confirmation before rekeying when
# the set of keys to be used has changed.
ansible_vault_skip_confirm_rekey_changes: false

# When set to True, verify that a new set of unseal keys is decryptable/usable
# by requiring them to be used for verification before committing to the unseal
# key change. This check reduces the chances of becoming locked out of Vault
# due to a misconfiguration.
ansible_vault_verify_rekey: true

# If set to True, skips the sanity check during cluster rekeying that the
# playbook is running against all cluster nodes.
#
# If you choose to set this option, you are responsible for manually
# propagating the new encrypted unseal key bundle to all hosts in the cluster.
# Take extreme care to copy the right files to the right hosts!
ansible_vault_skip_rekey_sanity_check: false
