---

- name: Decide whether to create an ephemeral GnuPG home
  run_once: true
  set_fact:
    # Detect the nesting level of this role to skip doing anything except
    # during the outer-most invocations
    ansible_vault_gnupg_home_nesting_level: "{{ (ansible_vault_gnupg_home_nesting_level|default(0)|int) + 1}}"

- run_once: true
  when: ansible_vault_gnupg_home_nesting_level|int == 1
  block:
    - name: Create ephemeral GnuPG home
      bbcrd.vault.create_ephemeral_gnupg_home:
        set_fact: ansible_vault_gnupg_home
      changed_when: false  # Don't pollute change logs
    
    # The create_ephemeral_gnupg_home module will try to gracefully shut down
    # any existing gpg-agent instances so in an ideal world this wouldn't be
    # necessary. Unfortunately, gpg-agents belonging to long-forgotten
    # temporary GnuPG homes which weren't correctly cleaned up cannot be
    # gracefully shut down, hence this step.
    - name: Stop any existing gpg-agents
      delegate_to: localhost
      become: false
      command:
        argv: ["killall", "gpg-agent"]
      changed_when: false
      failed_when: false
    
    - name: Import public keys
      bbcrd.vault.pgp_import:
        public_key: "{{ item.value.ansible_vault_pgp_public_key }}"
        gnupg_home: "{{ ansible_vault_gnupg_home }}"
      when: item.value.ansible_vault_pgp_public_key is defined
      loop: |-
        {{ ansible_vault_administrators | dict2items }}
      loop_control:
        label: "{{ item.key }}"
      changed_when: false  # Don't pollute change logs
    
    - name: Detect PGP card
      bbcrd.vault.pgp_detect_card:
        gnupg_home: "{{ ansible_vault_gnupg_home }}"
      changed_when: false  # Don't pollute change logs
    
    # In the step below we encrypt then decrypt dummy data using the private
    # key(s) detected on the PGP card. If the card has a PIN configured, this
    # will cause the PIN prompt to be shown. This has two benefits: first we
    # can fail early if the user doesn't know their PIN and second the PIN will
    # be cached for the remainder of the playbook. This avoids PIN prompt
    # timeouts occurring whilst a playbook runs in the background.
    - name: Pre-check all private key PINs
      tags: ansible_vault_precheck_pin
      block:
        - name: Enumerate available private keys
          bbcrd.vault.pgp_list:
            type: private
            gnupg_home: "{{ ansible_vault_gnupg_home }}"
          register: private_keys
        
        - name: Encrypt dummy data
          bbcrd.vault.pgp_encrypt:
            plaintext: "{{ 'dummy data' | b64encode() }}"
            public_key: "{{ item }}"
            gnupg_home: "{{ ansible_vault_gnupg_home }}"
          loop: "{{ private_keys.fingerprints }}"
          register: dummy_data
        
        - name: Decrypt dummy data (to trigger PIN entry)
          bbcrd.vault.pgp_decrypt:
            ciphertext: "{{ item }}"
            gnupg_home: "{{ ansible_vault_gnupg_home }}"
          loop_control:
            label: "<encrypted dummy data>"
          loop: "{{ dummy_data.results | map(attribute='ciphertext') }}"
