---

################################################################################
# Installation-related variables
################################################################################

# The version of vault to be installed
ansible_vault_version: "1.17.1"

# Location of the Vault server configuration directory
#
# Within this directory, the following files are placed:
# * config.hcl -- The vault server configuration file
ansible_vault_config_dir: "/etc/vault"

# The name (not path) of the vault server systemd service
ansible_vault_systemd_unit: vault

# User and group to run the vault service as
ansible_vault_user: "vault"
ansible_vault_group: "vault"
