---

################################################################################
# Cluster options
################################################################################

# The name of the Ansible group in which all members of the vault cluster are
# enumerated.
ansible_vault_cluster_ansible_group_name: vault


################################################################################
# Installation-related variables
################################################################################

# The version of vault to be installed
ansible_vault_version: "1.17.1"

# The name (not path) of the vault server systemd service
ansible_vault_systemd_unit: vault

# User and group to run the vault service as
ansible_vault_user: "vault"
ansible_vault_group: "vault"


################################################################################
# Vault server configuration
################################################################################

# Location of the Vault server configuration directory
#
# Within this directory, the following files are placed:
# * config.hcl -- The vault server configuration file
ansible_vault_config_dir: "/etc/vault"

# Location of the Vault server data directory
#
# Within this directory, the following are used
# * data/ -- The on-disk Raft storage location
# * encrypted_unseal_keys.json -- PGP encrypted unseal keys
# * encrypted_unseal_keys.json.candidate -- Candidate PGP encrypted unseal
#   keys, subject to verification during rekeying.
ansible_vault_data_dir: "/var/lib/vault"

# The base URL the server's API is reachable from publicly.
#
# By contrast, if you're using a reverse proxy (e.g. haproxy) to do HTTPS
# termination (for example) then the public address, port and protocol may
# differ. For example, you may listen on HTTP on 127.0.0.1 but have a public
# interface using HTTPS on some public IP address.
#
# XXX: Whilst 'ansible_vault_public_url' is defined as a default here, it
# *must* be defined for hosts using this role due to a limitation of Ansible.
# You're welcome to copy this default, of course!
ansible_vault_public_url: >-
  https://{{
    ansible_host | default(inventory_hostname)
  }}:8200


################################################################################
# TLS certificates
################################################################################

# Filename on the remote host of the CA PEM file to use to verify the vault
# server's HTTPS certificate. Omit to use default trust stores.
#ansible_vault_ca_path: "/path/to/ca.pem"


################################################################################
# Unseal key management
################################################################################

# A dictionary enumerating the vault administrators, i.e. the persons who will
# have access to unseal keys.
#
# Each user may have the following entries:
#
# * ansible_vault_pgp_public_key: (Required) The base64-encoded PGP public key
#   of the user. This will be used to encrypt unseal all needed keys.
# * ansible_vault_unseal_key_shares: (Optional) The number of key shares to
#   generate for this user. Defaults to 1.
#
# Example:
#
#     ansible_vault_administrators:
#       foo:
#         ansible_vault_pgp_public_key: "<ASCII Armor encoded PGP public key>"
#         ansible_vault_unseal_key_shares: 1
ansible_vault_administrators: {}

# The number of unseal keys which must be provided to unseal vault.
ansible_vault_unseal_key_threshold: 1

# Override: The a set of one or more (unencrypted) unseal key to use for
# unsealing vault nodes. If not given, the unseal key will be decrypted
# automatically using GnuPG.
ansible_vault_unseal_keys: null

# Override: A list of fingerprints for the PGP key to use to decrypt unseal
# keys. By default, any and all available private keys will be used which are
# available in the current GnuPG store.
ansible_vault_pgp_key_fingerprints: "{{ lookup('bbcrd.ansible_vault.pgp_private_key_fingerprints', wantlist=True) }}"

# Override: If not null, the supplied task file will be imported whenever
# additional unseal keys are required. The following variables will be set:
#
# * purpose -- a short string like 'to unseal vault' describing in a
#   human-readable manner the reason for the unseal keys being required
#
# * nonce -- the nonce for the operation (or null if unsealing nodes)
#
# * required -- the number of additional unseal keys which must be provided
#
# The main purpose for this hook is to facilitate automated testing of this
# role. It may, however, be useful as a way of (e.g.) automatically notifying
# colleagues when an unseal key is needed.
ansible_vault_provide_additional_unseal_keys_tasks: null


