---

################################################################################
# Cluster options
################################################################################

# The name of the Ansible group in which all members of the vault cluster are
# enumerated.
bbcrd_vault_cluster_ansible_group_name: vault


################################################################################
# Installation-related variables
################################################################################

# The version of vault to be installed
bbcrd_vault_version: "1.17.1"

# The name (not path) of the vault server systemd service
bbcrd_vault_systemd_unit: vault

# User and group to run the vault service as
bbcrd_vault_user: "vault"
bbcrd_vault_group: "vault"


################################################################################
# Vault server configuration
################################################################################

# Location of the Vault server configuration directory
#
# Within this directory, the following files are placed:
# * config.hcl -- The vault server configuration file
# * encrypted_unseal_keys.json -- PGP encrypted unseal keys
# * encrypted_unseal_keys.json.candidate -- Candidate PGP encrypted unseal
#   keys, subject to verification during rekeying.
bbcrd_vault_config_dir: "/etc/vault"

# Location of the Vault server data directory
#
# Within this directory, the following are used
# * data/ -- The on-disk Raft storage location
bbcrd_vault_data_dir: "/var/lib/vault"

# The base URL the server's API is reachable from publicly.
#
# By contrast, if you're using a reverse proxy (e.g. haproxy) to do HTTPS
# termination (for example) then the public address, port and protocol may
# differ. For example, you may listen on HTTP on 127.0.0.1 but have a public
# interface using HTTPS on some public IP address.
#
# XXX: Whilst 'bbcrd_vault_public_url' is defined as a default here, it
# *must* be defined for hosts using this role due to a limitation of Ansible.
# You're welcome to copy this default, of course!
bbcrd_vault_public_url: >-
  https://{{
    ansible_host | default(inventory_hostname)
  }}:8200


################################################################################
# TLS certificates
################################################################################

# Filename on the remote host of the CA PEM file to use to verify the vault
# server's HTTPS certificate. Omit to use default trust stores.
#bbcrd_vault_ca_path: "/path/to/ca.pem"


################################################################################
# Unseal key management
################################################################################

# The GnuPG home directory (on the Ansible control node) to use for all PGP
# operations. If null, the system's GnuPG home will be used.
bbcrd_vault_gnupg_home: null

# A dictionary enumerating the vault administrators, i.e. the persons who will
# have access to unseal keys.
#
# Each user may have the following entries:
#
# * bbcrd_vault_pgp_public_key: (Required) The ASCII armored PGP public key
#   of the user. This will be used to encrypt unseal all needed keys.  If this
#   key is absent, the entry in bbcrd_vault_administrators will be ignored for
#   the purposes of unseal key management.
# * bbcrd_vault_unseal_key_shares: (Optional) The number of key shares to
#   generate for this user. Defaults to 1.
#
# Example:
#
#     bbcrd_vault_administrators:
#       foo:
#         bbcrd_vault_pgp_public_key: "<ASCII Armor encoded PGP public key>"
#         bbcrd_vault_unseal_key_shares: 1
bbcrd_vault_administrators: {}

# The number of unseal keys which must be provided to unseal vault.
bbcrd_vault_unseal_key_threshold: 1

# Override: The a set of one or more (unencrypted) unseal key to use for
# unsealing vault nodes. If not given, the unseal key will be decrypted
# automatically using GnuPG.
bbcrd_vault_unseal_keys: null

# Override: A list of fingerprints of the PGP keys to use to decrypt unseal
# keys. If null, any and all available private keys will be used which are
# available in the current GnuPG store.
bbcrd_vault_pgp_key_fingerprints: null


################################################################################
# Safety overrides
################################################################################

# Don't log results of sensitive actions
bbcrd_vault_no_log_sensitive: true
