---

# A sufficiently powerful vault token.
#
#bbcrd_vault_root_token: "..."

# The audit engine type (see vault docs)
#
# Default to simple file-based auditing
bbcrd_vault_audit_type: file

# The mountpoint of the audit engine (without the trailing slash)
bbcrd_vault_audit_mount: stdout

# Human readable description of the audit engine
bbcrd_vault_audit_description: Send audit logs to stdout

# Audit engine options (see specific audit engine docs)
#
# Default (with bbcrd_vault_audit_type = file) is to write the audit log to
# stdout.
bbcrd_vault_audit_options:
  file_path: stdout

# A policy which allows holders the ability to compute the hash of an arbitrary
# value using the auditing engine's HMAC.
bbcrd_vault_audit_hash_policy_name: "audit_hash"
