- run_once: true
  block:
    - name: Enable KV secrets engine
      bbcrd.vault.vault_secrets_engine:
        mount: "{{ bbcrd_vault_kv_mount }}"
        type: kv
        options:
          version: "{{ bbcrd_vault_kv_version | string }}"
        vault_url: "{{ bbcrd_vault_public_url }}"
        vault_token: "{{ bbcrd_vault_root_token }}"
        vault_ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"

    - name: Create admin policy
      bbcrd.vault.vault_policy:
        name: "{{ bbcrd_vault_kv_admin_policy_name }}"
        policy: |-
          path "{{ bbcrd_vault_kv_mount }}/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
        vault_url: "{{ bbcrd_vault_public_url }}"
        vault_token: "{{ bbcrd_vault_root_token }}"
        vault_ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"

    - name: Create read-only policy
      bbcrd.vault.vault_policy:
        name: "{{ bbcrd_vault_kv_read_only_policy_name }}"
        policy: |-
          path "{{ bbcrd_vault_kv_mount }}/*" {
            capabilities = ["read", "list"]
          }
        vault_url: "{{ bbcrd_vault_public_url }}"
        vault_token: "{{ bbcrd_vault_root_token }}"
        vault_ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
