---
# Ensure unseal keys are present in ansible_vault_unseal_keys (i.e. it is not
# null). If unseal keys are already stored there, do nothing. Otherwise, load
# the unseal keys from an encrypted unseal key bundle.
#
# The encrypted unseal keys are read from the file named by
# encrypted_unseal_keys_filename. See fetch_encrypted_unseal_keys.yml.

- name: Obtain unseal keys
  any_errors_fatal: true
  when: ansible_vault_unseal_keys is none
  block:
    - name: Fetch encrypted unseal keys
      import_tasks: fetch_encrypted_unseal_keys.yml
    
    - name: Decrypt the unseal keys
      run_once: true
      no_log: "{{ ansible_vault_no_log_sensitive }}"
      set_fact:
        ansible_vault_unseal_keys: |-
          {{
            encrypted_unseal_keys.shares
              | selectattr("fingerprint", "in", ansible_vault_pgp_key_fingerprints)
              | map(attribute="encrypted_unseal_key")
              | map("bbcrd.ansible_vault.pgp_decrypt")
              | map("b64decode")
          }}
        unseal_keys_decrypted: true

    - name: Check we have at least one unseal key
      run_once: true
      assert:
        that: (ansible_vault_unseal_keys | length) >= 1
        fail_msg: "No unseal keys could be decrypted."
        quiet: true
