---

# This set of tasks propagates the encrypted unseal keys file to all hosts
# which don't currently have a copy of it -- i.e. new members of the cluster.
#
# We specifically *don't* attempt to make an inconsistent situation consistent
# since we don't have enough information to do this!

# NB: These tasks will fail if the encrypted unseal keys on the other servers
# are already inconsistent
- name: Fetch encrypted unseal keys
  import_role:
    name: bbcrd.ansible_vault.decrypt_unseal_keys
    tasks_from: fetch.yml

- name: Propagate encrypted unseal keys to new nodes
  copy:
    content: "{{ encrypted_unseal_keys | to_nice_json }}"
    dest: "{{ ansible_vault_data_dir }}/encrypted_unseal_keys.json"
    force: false  # Only write to hosts which don't already have keys installed
    backup: true  # Redundant, but I'm paranoid
