---

# Perform the vault commands necessary for unsealing
#
# Intended only for importing by unseal.yml

- name: Reset the unseal process
  uri:
    # vault operator unseal -reset
    url: "{{ ansible_vault_public_url }}/v1/sys/unseal"
    method: POST
    body_format: json
    body:
      reset: true
    ca_path: "{{ ansible_vault_ca_path | default(omit) }}"
  changed_when: true

- name: Supply unseal keys
  import_tasks: generic_unseal_key_flow.yml
  vars:
    purpose: "to unseal vault"
    nonce: null
    # vault status
    status_api_url: "{{ ansible_vault_public_url }}/v1/sys/seal-status"
    # vault operator unseal
    submit_api_url: "{{ ansible_vault_public_url }}/v1/sys/unseal"

