- name: Install backup script dependencies
  apt:
    name:
      - curl
      - jq
      - zip

- name: Create backup directory
  file:
    path: "{{ ansible_vault_backup_location }}"
    owner: "{{ ansible_vault_backup_user }}"
    group: "{{ ansible_vault_backup_group }}"
    state: directory
    mode: "0750"

- name: Install systemd unit
  template:
    src: vault_backup.service.j2
    dest: "/etc/systemd/system/{{ ansible_vault_backup_systemd_unit }}.service"

- name: Install systemd timer
  template:
    src: vault_backup.timer.j2
    dest: "/etc/systemd/system/{{ ansible_vault_backup_systemd_unit }}.timer"

- name: Install backup script
  copy:
    src: vault_backup.sh
    dest: "{{ ansible_vault_backup_script }}"
    mode: "0755"

- name: Start and enable systemd timer
  systemd:
    name: "{{ ansible_vault_backup_systemd_unit }}.timer"
    state: started
    enabled: true
    daemon_reload: true
