# See: https://www.jeffgeerling.com/blog/2024/fixing-curl-install-failures-ansible-on-red-hat-derivative-oses
- name: Ensure curl-minimal doesn't conflict with curl on RHEL
  when: ansible_os_family == "RedHat"
  dnf:
    name: curl
    allowerasing: true
    state: present

- name: Install backup script dependencies
  package:
    name:
      - curl
      - jq
      - zip

- name: Create backup directory
  file:
    path: "{{ bbcrd_vault_backup_location }}"
    owner: "{{ bbcrd_vault_backup_user }}"
    group: "{{ bbcrd_vault_backup_group }}"
    state: directory
    mode: "0750"

- name: Install systemd unit
  template:
    src: vault_backup.service.j2
    dest: "/etc/systemd/system/{{ bbcrd_vault_backup_systemd_unit }}.service"

- name: Install systemd timer
  template:
    src: vault_backup.timer.j2
    dest: "/etc/systemd/system/{{ bbcrd_vault_backup_systemd_unit }}.timer"

- name: Install backup script
  copy:
    src: vault_backup.sh
    dest: "{{ bbcrd_vault_backup_script }}"
    mode: "0755"

- name: Start and enable systemd timer
  systemd:
    name: "{{ bbcrd_vault_backup_systemd_unit }}.timer"
    state: started
    enabled: true
    daemon_reload: true

- name: Ensure needrestart config directory exists
  file:
    path: "/etc/needrestart/conf.d/"
    state: directory

- name: Prevent needrestart from restarting the backup script
  template:
    src: "needrestart.conf.j2"
    dest: "/etc/needrestart/conf.d/{{ bbcrd_vault_backup_systemd_unit }}.conf"
