---

- name: Check if Vault requires a restart
  when: |-
    bbcrd_vault_restart is none
    and not bbcrd_vault_restart_required
  block:
    - name: Check whether a restart is required
      include_tasks: check_if_restart_required.yml

- name: Determine which servers need restarting
  set_fact:
    will_restart: |-
      {{
        bbcrd_vault_restart
        if bbcrd_vault_restart is not none else
        bbcrd_vault_restart_required
      }}

- name: Enumerate the servers which will be restarted
  set_fact:
    all_restarted_hosts: |-
      {{
        groups[bbcrd_vault_cluster_ansible_group_name]
        | map("extract", hostvars)
        | selectattr("will_restart", "true")
        | map(attribute="inventory_hostname")
      }}

- name: Restart vault servers as required
  when: "all_restarted_hosts | length > 0"
  block:
    - name: Restart and unseal vault server
      include_tasks: restart_one_server.yml
      loop: "{{ all_restarted_hosts }}"
      loop_control:
        loop_var: target
    
    - name: Wait for restarted hosts to become responsive
      when: inventory_hostname in all_restarted_hosts
      import_role:
        name: bbcrd.vault.wait_for_api_responsiveness
