---

- name: Add new users to vault
  import_playbook: converge.yml
  vars:
    ansible_vault_skip_confirm_rekey_changes: true
    enabled_administrators:
      - test-user-1
      - test-user-2

- name: Verify new administrator added
  hosts: vault
  
  tasks:
    - name: Fetch new unseal keys
      import_tasks: tests/decrypt_unseal_keys.yml
    
    - name: Verify unseal keys changed
      assert:
        that: unseal_key_users | sort == ['test-user-1', 'test-user-1', 'test-user-1', 'test-user-2', 'test-user-2']
        quiet: true

- name: Remove added users again
  import_playbook: converge.yml
  vars:
    ansible_vault_skip_confirm_rekey_changes: true

- name: Verify administrators reverted back
  hosts: vault
  
  tasks:
    - name: Fetch new unseal keys
      import_tasks: tests/decrypt_unseal_keys.yml
    
    - name: Verify unseal keys changed
      assert:
        that: unseal_key_users | sort == ['test-user-1', 'test-user-1', 'test-user-1']
        quiet: true
