---
- name: Converge
  hosts: "{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  pre_tasks:
    - name: Import public key into ansible_vault_administrators
      include_vars:
        file: "{{ lookup('env', 'GNUPGHOME') }}/ansible_vault_administrators.yml"
        hash_behaviour: merge
  
  roles:
    - name: bbcrd.ansible_vault.vault
