---
# The following may be set to override the behaviour of this playbook:
#
# * ansible_vault_cluster_ansible_group_name -- Change the group of hosts to
#   run against
#
# * playbook_administrator_name -- The name of the administrator whose public
#   keys will used in the playbook (via ansible_vault_pgp_key_fingerprints)
#
# * enabled_administrators -- The set of administrators whose public keys are
#   included in the Ansible data in ansible_vault_administrators. Defaults to
#   ['test-user-1'].

- name: Converge
  hosts: "{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  pre_tasks:
    - name: Remove public keys from ansible_vault_administrators
      run_once: true
      set_fact:
        ansible_vault_administrators: |-
          {{
            ansible_vault_administrators.keys()
              | zip(
                ansible_vault_administrators.values()
                  | map('combine', {'ansible_vault_pgp_public_key': omit})
                )
              | community.general.dict
          }}
      tags: always
    
    - name: Import selected public keys into ansible_vault_administrators
      run_once: true
      set_fact:
        ansible_vault_administrators: |-
          {{
            ansible_vault_administrators
              | combine(
                  (
                    lookup(
                      'ansible.builtin.file',
                      lookup('env', 'GNUPGHOME') ~ '/ansible_vault_administrators_' ~ item ~ '.yml',
                    ) | from_yaml
                  ).ansible_vault_administrators,
                  recursive=True,
                )
          }}
      loop: "{{ enabled_administrators | default(['test-user-1']) }}"
      loop_control:
        label: "{{ lookup('env', 'GNUPGHOME') }}/ansible_vault_administrators_{{ item }}.yml"
      tags: always
    
    - name: Set ansible_vault_pgp_key_fingerprints
      run_once: true
      set_fact:
        ansible_vault_pgp_key_fingerprints: >-
          {{
            [
              ansible_vault_administrators
                [playbook_administrator_name | default('test-user-1')]
                .ansible_vault_pgp_public_key
                | b64encode
                | bbcrd.ansible_vault.pgp_public_key_to_fingerprint
            ]
          }}
      tags: always
  
  roles:
    - name: bbcrd.ansible_vault.vault


- name: Clean up any non-cluster memebers
  hosts: "all,!{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  tasks:
    - name: Shutdown vault server
      systemd:
        name: vault
        state: stopped
      ignore_errors: true  # Vault may not be installed
      tags: always
    
    - name: Delete all vault data
      file:
        path: /var/lib/vault
        state: absent
      tags: always
