---

# This top-level task is intended to be used to generate an ephemeral root
# token for interactive use. This is intended only for use in emergencies or
# highly unusual situations.
#
# The generated root token will be revoked when the playbook exits and will
# otherwise have a lifetime limited by ansible_vault_root_token_ttl.
#
# Example invocation:
#
#    - include_role:
#        name: bbcrd.ansible_vault.vault
#        tasks_from: generate_root_token.yml

- name: Obtain root token
  import_role:
    name: bbcrd.ansible_vault.generate_root

- block:
    - name: Display root token
      run_once: true
      debug:
        msg:
          ansible_vault_root_token: "{{ ansible_vault_root_token }}"
          ansible_vault_root_token_ttl: "{{ ansible_vault_root_token_ttl }}"


    - name: Wait for user to confirm finished with root token
      run_once: true
      pause:
        prompt: "Press enter to revoke root token {{ ansible_vault_root_token }}"

  always:
    - name: Revoke root token
      import_role:
        name: bbcrd.ansible_vault.generate_root
        tasks_from: revoke.yml
