---

# This top-level task is intended to be used to supply additional unseal keys
# to a vault cluster. It is intended to be called by other key holders when
# requested by another person is running the main tasks in this role.
#
# Example invocation:
#
#    - include_role:
#        name: bbcrd.ansible_vault.vault
#        tasks_from: supply_additional_keys.yml
#

- name: Provide keys for unsealing vault
  import_tasks: subtasks/generic_additional_unseal_key_flow.yml
  vars:
    purpose: "to unseal vault"
    submit_once: false
    # vault status
    status_api_url: "{{ ansible_vault_public_url }}/v1/sys/seal-status"
    # vault operator unseal
    submit_api_url: "{{ ansible_vault_public_url }}/v1/sys/unseal"
  tags: ansible_vault_supply_unseal_keys

- name: Supply unseal keys for root token generation
  import_tasks: subtasks/generic_additional_unseal_key_flow.yml
  vars:
    purpose: "to generate a root token"
    submit_once: true
    status_api_url: "{{ ansible_vault_public_url }}/v1/sys/generate-root/attempt"
    # vault operator generate-root ...
    submit_api_url: "{{ ansible_vault_public_url }}/v1/sys/generate-root/update"
  tags: ansible_vault_supply_generate_root_keys

- name: "Check if rekey verification in progress"
  run_once: true
  uri:
    url: "{{ ansible_vault_public_url }}/v1/sys/rekey/verify"
    ca_path: "{{ ansible_vault_ca_path | default(omit) }}"
    # NB: 400 returned by verify endpoint when no verification is in progress.
    # NB: 503 returned if vault is sealed
    status_code: [200, 400, 503]
  register: verify_status

- name: Supply unseal keys for rekeying
  # NB: The rekeying endpoint does not provide any indication that rekeying has
  # completed and that verification is in progress. As such, to avoid
  # erroneously submitting keys at this point we pre-check to make sure
  # verification is not taking place.
  when: verify_status.json.nonce | default("") == ""
  import_tasks: subtasks/generic_additional_unseal_key_flow.yml
  vars:
    purpose: "to rekey vault"
    submit_once: true
    status_api_url: "{{ ansible_vault_public_url }}/v1/sys/rekey/init"
    # vault operator rekey
    submit_api_url: "{{ ansible_vault_public_url }}/v1/sys/rekey/update"
  tags: ansible_vault_supply_rekey_keys

- name: Supply candidate unseal keys to verify rekey
  import_tasks: subtasks/generic_additional_unseal_key_flow.yml
  vars:
    purpose: "to verify new unseal keys"
    submit_once: true
    status_api_url: "{{ ansible_vault_public_url }}/v1/sys/rekey/verify"
    # vault operator rekey -verify ...
    submit_api_url: "{{ ansible_vault_public_url }}/v1/sys/rekey/verify"
    encrypted_unseal_keys_filename: "encrypted_unseal_keys.json.candidate"
    status_status_code: [200, 400, 503]  # Returns 400 when no verification in progress
  tags: ansible_vault_supply_verify_keys
