---

# Wait for a node to be responsive to API requests. This is necessary after
# unsealing/joining a node to the cluster since nodes will report being
# unsealed before they're capable of making API requests.

# Here we use the root-key generation status API endpoint to verify cluster
# membership (at least sufficient membership for API calls to be possible)
# since we can call this without a valid token.
#
# This wait is necessary since when a host is unsealed and joins the cluster,
# it will not immediately be able to make API calls.
- name: Wait for all cluster nodes to respond to API requests
  uri:
    url: "{{ ansible_vault_public_url }}/v1/sys/generate-root/attempt"
    ca_path: "{{ ansible_vault_ca_path | default(omit) }}"
  register: vault_api_call
  retries: 20
  delay: 2
  until: vault_api_call.status == 200
