---

# Send the vault API commands to unseal nodes

- name: Reset the unseal process
  uri:
    # vault operator unseal -reset
    url: "{{ bbcrd_vault_public_url }}/v1/sys/unseal"
    method: POST
    body_format: json
    body:
      reset: true
    ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
  changed_when: true

- name: Supply unseal keys
  import_role:
    name: bbcrd.vault.generic_unseal_key_submission_flow
  vars:
    purpose: "to unseal vault"
    nonce: null
    # vault status
    status_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/seal-status"
    # vault operator unseal
    submit_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/unseal"
    # When unsealing a node for the first time (i.e. joining it to the
    # cluster), the unseal API doesn't return "sealed: false" immediately. As
    # such, we postpone this check to allow us to wait as necessary
    check_complete: false

- name: Confirm vault is unsealed
  uri:
    url: "{{ bbcrd_vault_public_url }}/v1/sys/seal-status"
    ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
  register: status
  retries: 30
  delay: 2
  until: >-
    (status.status == 200 and not status.json.sealed)
