---

- name: Enumerate decryptable unseal keys
  run_once: true
  set_fact:
    decryptable_unseal_keys: |-
      {{
        encrypted_unseal_keys.shares
          | selectattr("fingerprint", "in", ansible_vault_pgp_key_fingerprints)
      }}

- name: Check we can use at least one unseal key
  run_once: true
  assert:
    that: "{{ decryptable_unseal_keys | length >= 1 }}"
    fail_msg: "No unseal keys can be decrypted."
    quiet: true

- name: Decrypt the unseal keys
  run_once: true
  no_log: "{{ ansible_vault_no_log_sensitive }}"
  set_fact:
    ansible_vault_unseal_keys: |-
      {{
        decryptable_unseal_keys
          | map(attribute="encrypted_unseal_key")
          | map("bbcrd.ansible_vault.pgp_decrypt")
          | map("b64decode")
      }}
    unseal_keys_decrypted: true
