---

- name: Decrypt the unseal keys
  run_once: true
  no_log: "{{ ansible_vault_no_log_sensitive }}"
  set_fact:
    ansible_vault_unseal_keys: |-
      {{
        encrypted_unseal_keys.shares
          | selectattr("fingerprint", "in", ansible_vault_pgp_key_fingerprints)
          | map(attribute="encrypted_unseal_key")
          | map("bbcrd.ansible_vault.pgp_decrypt")
          | map("b64decode")
      }}
    unseal_keys_decrypted: true

- name: Check we have at least one unseal key
  run_once: true
  assert:
    that: (ansible_vault_unseal_keys | length) >= 1
    fail_msg: "No unseal keys could be decrypted."
    quiet: true
