- name: Fetch and decrypt unseal keys if not already loaded
  when: (bbcrd_vault_unseal_keys | default(None)) is none
  block:
    - name: Fetch encrypted unseal keys
      import_tasks: fetch.yml

    - name: Decrypt unseal keys
      import_tasks: decrypt.yml
