---

# We use the root-key generation status API endpoint to verify cluster
# membership. This API is a cluster-wide command (i.e. requires cluster
# membership) but doesn't require a valid token of any kind.

- name: Wait for all cluster nodes to respond to API requests
  uri:
    url: "{{ ansible_vault_public_url }}/v1/sys/generate-root/attempt"
    ca_path: "{{ ansible_vault_ca_path | default(omit) }}"
  register: vault_api_call
  retries: 20
  delay: 2
  until: vault_api_call.status == 200
