---

# One or more unseal keys.
#
#bbcrd_vault_unseal_keys: [...]

# A sufficiently powerful vault token.
#
#bbcrd_vault_root_token: "..."

# A flag which may be set indicating that a given Vault server needs restarting
# (e.g. because its configuration changed).
#
# See bbcrd_vault_restart for the variable which can be used to force/prevent
# restarts, rather than just indicate that one is desireable.
#
# This role will automatically set this to true if the Vault binary is out of
# date or if the systemd or Vault config files have changed since Vault was
# started.
#
# If a restart is performed, this flag will be cleared.
bbcrd_vault_restart_required: false

# Override restart behaviour (intended to be set on a server-by-server basis).
#
# If null (the default if unspecified), restart the server if the running vault
# version does not match the installed version, or if any configuration files
# have changed since Vault started.
#
# If truthy, always restart the server.
#
# If False, do not restart the server (even if there has been a version or
# config file change since Vault started).
bbcrd_vault_restart: null


# If set to False, this role will refuse to restart cluster nodes when doing so
# would cause the cluster to fall out of quorum during the restart.
bbcrd_vault_allow_loss_of_quorum_on_restart: false
