---
driver:
  name: docker

platforms:
  - &instance_config
    name: vault
    groups:
      - vault
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    override_command: false
    
    # Pass-through any proxy config
    env:
      http_proxy: "$http_proxy"
      https_proxy: "$https_proxy"
      no_proxy: "vault,$no_proxy"
    
    # Required to run systemd within docker
    privileged: true
    cgroupns_mode: host
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    
    # Internal network to allow communication between nodes
    networks:
      - name: internal
  
  # A pair of dummy hosts for testing approle deployment of machine credentials
  - <<: *instance_config
    name: machine-1
    groups:
      - machines
  
  - <<: *instance_config
    name: machine-2
    groups:
      - machines

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    
    # NB: Each group of tests executes as a 'side effect'. There is no converge
    # step.
    - side_effect tests/test_vault_audit.yml
    - side_effect tests/test_vault_auth_method.yml
    - side_effect tests/test_vault_entity.yml
    - side_effect tests/test_vault_group.yml
    - side_effect tests/test_vault_auth_method_entity_aliases.yml
    - side_effect tests/test_vault_policy.yml
    - side_effect tests/test_vault_oidc.yml
    - side_effect tests/test_vault_secrets_engine.yml
    - side_effect tests/test_vault_ssh_signer.yml
    - side_effect tests/test_vault_approles.yml
    - side_effect tests/test_vault_approle_secret.yml
    - side_effect tests/test_approle_roles.yml
    
    - cleanup
    - destroy

provisioner:
  config_options:
    connection:
      pipelining: true
  
  inventory:
    group_vars:
      all:
        ansible_vault_public_url: "http://vault:8200"
      
      vault:
        ansible_vault_version: "1.17.1"
        
        # No real secrets in the test suite!
        ansible_vault_no_log_sensitive: false
        
        # Use HTTP to avoid need to setup certificates in test environment
        ansible_vault_listen_protocol: http
        
        ansible_vault_approle:
          test_machines:
            token_policies:
              - foo
              - bar
    
      # Group for approle role testing
      machines:

    host_vars:
      # For approle role testing
      machine-1:
        ansible_vault_approle:
          test_machines:
            token_ttl: 60
      machine-2:
        ansible_vault_approle:
          test_machines:
            token_policies:
              - baz
