---

# Setup and manage a Vault cluster. Handles installation, unsealing nodes,
# managing cluster membership, rolling upgrades and unseal key management.
#
# This playbook (should be!) declarative and idempotent and largely consists of
# stringing together the major roles in this collection.

- name: Setup and manage a Vault cluster
  hosts: "{{ ansible_vault_cluster_ansible_group_name | default('vault') }}"
  
  tasks:
    - name: Install Vault software and systemd service
      import_role:
        name: bbcrd.ansible_vault.install
      tags:
        - ansible_vault_install

    - name: Write Vault server configuration files
      import_role:
        name: bbcrd.ansible_vault.configure_server
      tags:
        - ansible_vault_configure_server

    - name: Perform cluster-wide operations
      # All remaining tasks in this role enact logically cluster-wide operations.
      # Therefore, there is no sense in hobbling on if some node doesn't respond
      # correctly.
      any_errors_fatal: true
      block:
        - name: Initialise first vault node
          import_role:
            name: bbcrd.ansible_vault.init_first_node
          tags:
            - ansible_vault_init_first_node
        
        - name: Unseal the cluster (and join new nodes)
          import_role:
            name: bbcrd.ansible_vault.unseal
          tags:
            - ansible_vault_unseal
        
        - name: Propagate encrypted unseal keys to new nodes
          import_role:
            name: bbcrd.ansible_vault.propagate_unseal_keys
          tags:
            - ansible_vault_propagate_unseal_keys
        
        - name: Remove old nodes from the cluster
          import_role:
            name: bbcrd.ansible_vault.remove_old_cluster_nodes
          tags:
            - ansible_vault_remove_old_cluster_nodes
        
        # NB: This process is deliberately perormed *after* unsealing and pruning
        # the cluster of old nodes since it maximises the chances that the cluster
        # will be in a state where we can safely restart a server without causing
        # an outage.
        - name: Restart vault servers if required
          import_role:
            name: bbcrd.ansible_vault.restart
          tags:
            - ansible_vault_restart
        
        
        - name: Rekey unseal keys (e.g. to add/remove admins)
          import_role:
            name: bbcrd.ansible_vault.rekey
          tags:
            - ansible_vault_rekey
        
        # TODO: We should probably provide some facility for deploying vault
        # service configuration at this point (e.g. loading up policies and secrets
        # engines etc.)
      
      always:
        - name: Revoke any generated root tokens
          import_role:
            name: bbcrd.ansible_vault.generate_root
            tasks_from: revoke.yml
          tags:
            - always
            - ansible_vault_revoke_root_token
        
        - name: Clear any decrypted unseal keys
          import_role:
            name: bbcrd.ansible_vault.decrypt_unseal_keys
            tasks_from: clear.yml
          tags:
            - always
            - ansible_vault_clear_unesal_keys
