---

# Submit additional unseal keys to assist another vault administrator running
# one of the "main" roles/playbooks.
#
# This playbook will check for whether unseal keys are actively needed for any
# of the following tasks and automatically submit as many unseal keys as
# possible up to the number required.
#
# * Unsealing a vault node (or nodes)
# * Generating a root token
# * Rekeying
# * Verifying new unseal keys (during rekeying)
#
# Prior to submitting keys, the playbook will interactively confirm unseal key
# submission. For most operations this will include a nonce for the current
# operation. You should confirm that this matches the nonce reported by your
# colleague running the main role/playbook. This verifies that unseal keys are
# being submitted in service of the person/task you think they are!
#
# See documentation for the
# `bbcrd.vault.generic_unseal_key_submission_flow` and
# `bbcrd.vault.generic_additional_unseal_key_submission_flow` roles for
# more details of this process.

- name: Supply additional unseal keys to assist another administrator
  hosts: "{{ bbcrd_vault_cluster_ansible_group_name | default('vault') }}"
  become: "{{ bbcrd_vault_become | default(True) }}"

  tasks:
    - block:
        - name: Create ephemeral GnuPG environment for handling unseal keys
          import_role:
            name: bbcrd.vault.ephemeral_gnupg_home
          tags:
            - always
            - bbcrd_vault_ephemeral_gnupg_home
            # The molecule test suite uses its own GnuPG environment with its
            # own test keypairs.
            - molecule-notest

        # Below we deliberately try each of the different unseal tasks in the
        # reverse-order to the order they're performed in the
        # manage_vault_cluster playbook. This avoids a potential race condition
        # between this playbook and the management playbook in which this
        # playbook ends up submitting too many keys.
        
        - name: "Check if rekey verification in progress"
          run_once: true
          uri:
            url: "{{ bbcrd_vault_public_url }}/v1/sys/rekey/verify"
            ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
            # NB: 400 returned by verify endpoint when no verification is in progress.
            # NB: 503 returned if vault is sealed
            status_code: [200, 400, 503]
          register: verify_status
          tags: always
        
        - name: Supply candidate unseal keys for verification
          when: |-
            verify_status.json.nonce | default("") != ""
            and decrypt_candidate_unseal_keys_failed is not defined
          tags:
            - bbcrd_vault_supply_verify_keys
          block:
            - name: Skip rekey verification check if candidate keys not available
              block:
                - name: Decrypt candidate unseal keys
                  import_role:
                    name: bbcrd.vault.decrypt_unseal_keys
                  vars:
                    encrypted_unseal_keys_filename: "encrypted_unseal_keys.json.candidate"
              rescue:
                - name: Skip rekey verification if couldn't decrypt candidate unseal keys
                  set_fact:
                    decrypt_candidate_unseal_keys_failed: true

            - name: Supply candidate unseal keys to verify rekey
              import_role:
                name: bbcrd.vault.generic_additional_unseal_key_submission_flow
              vars:
                purpose: "to verify new unseal keys"
                submit_once: true
                status_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/rekey/verify"
                # vault operator rekey -verify ...
                submit_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/rekey/verify"
                status_status_code: [200, 400, 503]  # Returns 400 when no verification in progress
            
            - name: Clear candidate unseal keys
              set_fact:
                bbcrd_vault_unseal_keys: null
        
        - name: Decrypt unseal keys
          import_role:
            name: bbcrd.vault.decrypt_unseal_keys
          tags:
            - always

        - name: Supply unseal keys for rekeying
          # NB: The rekeying endpoint does not provide any indication that rekeying has
          # completed and that verification is in progress. As such, to avoid
          # erroneously submitting keys at this point we pre-check to make sure
          # verification is not taking place.
          when: verify_status.json.nonce | default("") == ""
          import_role:
            name: bbcrd.vault.generic_additional_unseal_key_submission_flow
          vars:
            purpose: "to rekey vault"
            submit_once: true
            status_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/rekey/init"
            # vault operator rekey
            submit_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/rekey/update"
          tags: bbcrd_vault_supply_rekey_keys

        - name: Supply unseal keys for root token generation
          import_role:
            name: bbcrd.vault.generic_additional_unseal_key_submission_flow
          vars:
            purpose: "to generate a root token"
            submit_once: true
            status_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/generate-root/attempt"
            # vault operator generate-root ...
            submit_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/generate-root/update"
          tags: bbcrd_vault_supply_generate_root_keys
        
        - name: Provide keys for unsealing vault
          import_role:
            name: bbcrd.vault.generic_additional_unseal_key_submission_flow
          vars:
            purpose: "to unseal vault"
            submit_once: false
            # vault status
            status_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/seal-status"
            # vault operator unseal
            submit_api_url: "{{ bbcrd_vault_public_url }}/v1/sys/unseal"
          tags: bbcrd_vault_supply_unseal_keys

      always:
        - name: Clear any decrypted unseal keys
          import_role:
            name: bbcrd.vault.decrypt_unseal_keys
            tasks_from: clear.yml
          tags:
            - always
            - bbcrd_vault_clear_unesal_keys
        
        - name: Clean up ephemeral GnuPG environment
          import_role:
            name: bbcrd.vault.ephemeral_gnupg_home
            tasks_from: cleanup.yml
          tags:
            - always
            - bbcrd_vault_ephemeral_gnupg_home
