

################################################################################
# Forced action overrides
################################################################################

# Override: Set to a list of servers to be restarted (and unsealed again)
# one-by-one, in the order specified during the execution of the role.
#
# If null, only servers running an out-of-date vault binary will be restarted.
#
# If an empty list, no servers will be restarted, even if some are running an
# out-of-date version.
#
# If a list, exactly the listed set of servers will be restarted, regardless of
# what Vault versions are in use.
ansible_vault_restart_servers: null

# Override: If set to True, rekey the unseal keys even if the set of managers
# has not changed.
ansible_vault_force_rekey: false


################################################################################
# Safety overrides
################################################################################

# If set to False, this role will refuse to restart cluster nodes when doing so
# would cause the cluster to fall out of quorum during the restart.
ansible_vault_allow_loss_of_quorum_on_restart: false

# If set to True, skips the sanity check during new cluster initialisation that
# the playbook is running against all cluster nodes.
ansible_vault_skip_cluster_init_sanity_check: false

# When set, do not interactively prompt for confirmation before rekeying when
# the set of keys to be used has changed.
ansible_vault_skip_confirm_rekey_changes: false

# When set to True, verify that a new set of unseal keys is decryptable/usable
# by requiring them to be used for verification before committing to the unseal
# key change. This check reduces the chances of becoming locked out of Vault
# due to a misconfiguration.
ansible_vault_verify_rekey: true

# If set to True, skips the sanity check during cluster rekeying that the
# playbook is running against all cluster nodes.
#
# If you choose to set this option, you are responsible for manually
# propagating the new encrypted unseal key bundle to all hosts in the cluster.
# Take extreme care to copy the right files to the right hosts!
ansible_vault_skip_rekey_sanity_check: false

# If true, skip interactive confirmation (and verification of the nonce, if
# applicable) before supplying additional unseal keys.
ansible_vault_skip_additional_unseal_confirmation: false
