################################################################################
# Safety overrides
################################################################################

# If true, skip interactive confirmation (and verification of the nonce, if
# applicable) before supplying additional unseal keys.
ansible_vault_skip_additional_unseal_confirmation: false
