---
# Remove all nodes from the vault HA cluster which do not appear in the group.
# This is important since if these are left in the database, the quorum size
# may be larger than it needs to be.

- name: Remove any old nodes from the cluster
  run_once: true
  block:
    - name: Get raft autopilot state
      no_log: "{{ bbcrd_vault_no_log_sensitive }}"
      uri:
        # vault operator raft autopilot state
        url: "{{ bbcrd_vault_public_url }}/v1/sys/storage/raft/autopilot/state"
        headers:
          X-Vault-Token: "{{ bbcrd_vault_root_token }}"
        ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
      register: vault_autopilot_state

    - name: Enumerate cluster members to remove
      set_fact:
        healthy_to_remove: |-
          {{
            vault_autopilot_state.json.data.servers.values()
              | selectattr("healthy", "true")
              | map(attribute="id")
              | difference(groups[bbcrd_vault_cluster_ansible_group_name])
          }}
        unhealthy_to_remove: |-
          {{
            vault_autopilot_state.json.data.servers.values()
              | selectattr("healthy", "false")
              | map(attribute="id")
              | difference(groups[bbcrd_vault_cluster_ansible_group_name])
          }}
        healthy_to_keep: |-
          {{
            vault_autopilot_state.json.data.servers.values()
              | selectattr("healthy", "true")
              | map(attribute="id")
              | intersect(groups[bbcrd_vault_cluster_ansible_group_name])
          }}
        unhealthy_to_keep: |-
          {{
            vault_autopilot_state.json.data.servers.values()
              | selectattr("healthy", "false")
              | map(attribute="id")
              | intersect(groups[bbcrd_vault_cluster_ansible_group_name])
          }}

    - name: Check that removing nodes won't cause the cluster to lose quorum
      when: not bbcrd_vault_allow_loss_of_quorum_on_cluster_node_removal
      assert:
        that: "{{ (healthy_to_keep | length) > (unhealthy_to_keep | length) }}"
        fail_msg: >-
          After removing old nodes, the ratio of healthy to unhealthy nodes
          will become {{ healthy_to_keep | length }}:{{ unhealthy_to_keep | length }}
          which would lead to a loss of quorum.
        quiet: true

    - name: Remove old cluster members
      no_log: "{{ bbcrd_vault_no_log_sensitive }}"
      uri:
        # vault operator raft remove-peer
        url: "{{ bbcrd_vault_public_url }}/v1/sys/storage/raft/remove-peer"
        method: POST
        body_format: json
        body:
          server_id: "{{ item }}"
        headers:
          X-Vault-Token: "{{ bbcrd_vault_root_token }}"
        status_code: [200, 204]  # OK, No Content
        ca_path: "{{ bbcrd_vault_ca_path | default(omit) }}"
      changed_when: true
      loop: "{{ healthy_to_remove | union(unhealthy_to_remove) }}"
